### ISSUE TITLE
Amp menu

### ISSUE THREAD

**Issue by Lofesa** [tomusborne/amp-for-generatepress#2]
When in amp, the menu show but not the images associates, I will say, not the 3 bar nor the inverted ^.
The menu works, if you click in the space the inverted ^, then the menu is spanded.

![Captura](https://user-images.githubusercontent.com/22342793/70533275-0d748200-1b59-11ea-8b84-f85462fbe161.jpg)

The svg stuff is in the html but don´t show.

![Captura1](https://user-images.githubusercontent.com/22342793/70533514-8d025100-1b59-11ea-9471-b8c0a58ab9b3.JPG)

When in desktop it show
![Capture](https://user-images.githubusercontent.com/22342793/70565126-c22a9580-1b91-11ea-878f-cbd7395bbb49.jpeg)

**Comment by rsmith4321** [comment]
You can't use the svg icons yet with amp, it will work if you switch to the font icons.  Hopefully this will eventually be fixed.

**Comment by Lofesa** [comment]
Hi 
I have added the svg in the buttons and now I have the hamburger menu and the down arrow in amp pages.
Not animated cause I don´t know how to do it, but allmost the users have a clue to where click to deploy the submenus.

**Comment by tomusborne** [comment]
This issue is fixed in the master branch.
