### ISSUE TITLE
Illegal CSS Issue

### ISSUE THREAD

**Issue by ghost** [tomusborne/amp-for-generatepress#3]
Getting error with the file `generatepress/css/unsemantic-grid.min.css` for CSS rule `-ms-viewport`

![](https://i.imgur.com/ZIVirGC.png)

Attaching screenshot: https://imgur.com/a/74cpfbZ

**Comment by rsmith4321** [comment]
This isn't really a problem the amp plugin is just letting you know it removed invalid css but you can ignore these warnings.
